### ISSUE TITLE
How to send code blocks or emojis in text

### ISSUE THREAD

**Issue by SailReal** [pkulak/matui#13]
Thank you so much for this amazing matrix client :), just one (stupid) question: How do I correctly enter emojis like `:joy:` or code blocks 
\```
fooo
\```
Those values are passed 1:1 to the receiving client. I'm using Neovim, is this a configuration/understanding problem?

For emojis I could use the emoji directly like :joy: but this does not work for something like code blocks.

**Comment by pkulak** [comment]
If you're using latest, it _should_ just send markdown all the time, which means you can put in all the formatting you like and other clients should display it nicely, if they support markdown.

https://github.com/pkulak/matui/commit/e0e9cd27fef33ec1bc39048068aaae5a49efe50a

The emoji stuff would be a whole new feature to expand them. Maybe not too tough since the library is already there, but a bit of work, plus a config to enable/disable. I just have an emoji picker on my desktop and paste them in, personally.

**Comment by SailReal** [comment]
I can't believe it :man_facepalming: ...I didn't check the version before I tried to find the cause and finally opened the issue. AUR was still on 0.4.4, just marked it as deprecated and is now the latest where code blocks etc works as you say -.- 
Sorry for the noise.

Have put myself down as a co-maintainer there so hopefully that won't be out of date anytime soon.

Regarding the emoji picker I can also live with that, so closing this issue.

**Comment by pkulak** [comment]
Yeah, my bad there for letting the AUR get so out of date. Thanks for jumping on that. I switched distros like a month after I made that package, so I always forget to keep it updated. :D
